apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: product-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - image: gokumonkey/product-service:2
        name: product-microservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
